### ISSUE TITLE
Suggestion : Regarding Saving JSON Data 

### ISSUE THREAD

**Issue by jayanthchandra** [razorpay/ifsc-api#14]
Hey , 

Browsed the repo , found all the data stored in json in `/data` directory . Current app works through 
`banknames.json` -> `xyz_bank.json` , this could take two file operation for access. This could be ported to sqlite db having all the data stored there and could be used for accessing with ACID properties. 
With db implementation , Operation such as filtering across cities or entire bank is possible. 

 If there is a only one functionality served which is serving only ifsc code, this implementation is good enough . 

Let me know your views .

**Comment by captn3m0** [comment]
Hi @jayanthchandra, starting with a recent release, we are serving production traffic using the Docker container. The docker build step generates the redis database using the JSON files, and they are deleted.

The traffic is served off redis. Moreover, the additional files (sublet.json, banknames.json) are read only on the server boot and read of memory for all further operations.

We're looking to add more API functionality (such as state lookups) using the redis DB.
