### ISSUE TITLE
some ifsc codes giving branch names containing special characters

### ISSUE THREAD

**Issue by sriksm19** [razorpay/ifsc-api#16]
this one is for ICIC0006255. instead of MYSORE MAIN it has an additional á.

![image](https://user-images.githubusercontent.com/1223117/36854029-fe5dd7e8-1d95-11e8-860c-f95ad23957d1.png)

Would give you more soon if encountered.

**Comment by sriksm19** [comment]
just saw your icici.json file.. its almost everywhere in it
![image](https://user-images.githubusercontent.com/1223117/36854392-e24e3470-1d96-11e8-9c58-31678cdf0541.png)

**Comment by sriksm19** [comment]
just saw your ICICI.json file. looks like its almost everywhere in it
![image](https://user-images.githubusercontent.com/1223117/36854447-0506e4d0-1d97-11e8-9592-8d0349f30dff.png)

**Comment by captn3m0** [comment]
This is an encoding issue at RBI end. You can verify this by downloading the original RBI excel sheets as well.

See https://github.com/razorpay/ifsc/issues/32 and https://github.com/razorpay/ifsc/issues/29

If you have a suggestion on how this can be handled cleanly, feedback is welcome :+1:

**Comment by sriksm19** [comment]
https://stackoverflow.com/questions/10207354/how-to-remove-all-of-the-diacritics-from-a-file
would this help? (probably replace the diacritic with space or empty char)

or
https://stackoverflow.com/questions/3264915/remove-non-ascii-characters-in-a-file ?

PS: i havent written bash codes .. yet.. 

PPS: + i just mailed rbi regd this issue.. hope they check and correct it in this century

**Comment by captn3m0** [comment]
These are all encoding issues. Likely newlines and other characters getting converted. However, I'd rather have RBI fix these at their end.

**Comment by captn3m0** [comment]
RBI doesn't seem to be keen to fix these, so these are now cleaned up in the release. Accuracy is not guaranteed, but if you notice an issue starting [from 1.5.13 release](https://github.com/razorpay/ifsc/releases/tag/1.5.13) - please create a new issue.

Note that the changes aren't live at ifsc.razorpay.com yet, but should be there soon.
