### ISSUE TITLE
How does php  file work like a website

### ISSUE THREAD

**Issue by amitkumarsharma05** [razorpay/ifsc-api#57]
Dear sir,
I want to create a project on search IFSC code on PHP, I have downloaded your file but I can't understand how to use php folder, please help me to create a project IFSC code finder with PHP.

Thanks
Amit

**Comment by rajeevbbqq** [comment]
Hello Amit,

You can try with curl / guzzlehttp for making API requests In PHP.
Use the API endpoint https://ifsc.razorpay.com/ for fetch bank details.

Or use the official package `composer require php-http/curl-client razorpay/ifsc`
https://packagist.org/packages/razorpay/ifsc

**Comment by amitkumarsharma05** [comment]
Thanks for reply.

I not understood yet, i want to like this process on PHP

Add support for searching IFSC #41
1. First I have list of bank which I select
2. On selecting list I get states of bank
3. On Selecting State I get City of bank
4. On Selecting City I get branches of bank
5. On Selecting Branch I get details of branch

here are some examples of website
1. https://www.bankbazaar.com/ifsc-code.html
2.https://www.paisabazaar.com/ifsc-code/
3. https://bankifsccode.com/

Thanks
Amit

**Comment by captn3m0** [comment]
Search is currently not support on the API, but may happen in the future. Closing this for now.

**Comment by deepabehl** [comment]
There are collection of data where php script is just doing sorting function like this this [ifsc code finder](https://codeifsc.in/) tool website.
