### ISSUE TITLE
All wrong info for an IFSC code

### ISSUE THREAD

**Issue by prateekanilkedia** [razorpay/ifsc-api#74]
When I check for this IFSC code, PUNB0493400, on [https://ifsc.razorpay.com/PUNB0493400](https://ifsc.razorpay.com/PUNB0493400), I get all wrong information about the branch. When checking on [PNB's website](https://www.pnbindia.in/LocateUS.aspx) with location as "Lohar Patti Road Sikaria Niwas Kishanganj Distt Kishanganj", I get this IFSC (PUNB0493400) associated with it. 

But with Razorpay's API I get Delhi branch. Please find below the response we get from Razorpay's API.

`{"BRANCH":"DELHI, SANJAY GANDHI T.NGR","CENTRE":"DELHI","DISTRICT":"DELHI","STATE":"DELHI","ADDRESS":"AG-102 SANJAY GANDHI TRANSPORT NAGAR DL DELHI","CONTACT":"","UPI":true,"RTGS":true,"CITY":"DELHI","MICR":"855024002","NEFT":true,"IMPS":true,"BANK":"Punjab National Bank","BANKCODE":"PUNB","IFSC":"PUNB0493400"}
`

**Comment by captn3m0** [comment]
The details come from the RBI website itself: https://rbidocs.rbi.org.in/rdocs/RTGS/DOCs/RTGEB0815.xlsx (Linked at https://www.rbi.org.in/scripts/FAQView.aspx?Id=65)

Can't do anything here, perhaps reach out to RBI or the banks to get this corrected.
